version: '3.7'

services:

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
    - 54321:5432

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    command: "flask run --host=0.0.0.0 --port=8000"

  webpage:
    container_name: webpage
    build:
      context: ./webpage
      dockerfile: Dockerfile
    volumes:
      - './webpage:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
