version: '3.7'

services:
  webpage:
    container_name: webpage
    build:
      context: ./webpage
      dockerfile: Dockerfile
    volumes:
      - './webpage:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
